language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alikorna/docker-react -f Docker.dev .
  
script:
    - docker run -e CI=true alikorna/docker-react npm run test
